license="All rights reserved"

modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="diablomodif" #mandatory

version="1.16.3-1.0.0" #mandatory

displayName="Diablo" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to Toxeteer and Ewan Howell for The Warden Model/Texture!" #optional

authors="Cyno, Toxeteer, and Ewan Howell!" #optional

description=''' Diablo. The Guardian of The Heart of The Nether.'''



[[dependencies.diablomodif]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.diablomodif]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.diablomodif]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"